2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Configure stats pid to 27471
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Loading settings from /home/ieyeppo/.config/wandb/settings
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Loading settings from /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/base/wandb/settings
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_init.py:_log_setup():524] Logging user logs to /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/base/wandb/run-20250926_123904-ruhw9vo6/logs/debug.log
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_init.py:_log_setup():525] Logging internal logs to /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/base/wandb/run-20250926_123904-ruhw9vo6/logs/debug-internal.log
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_init.py:init():564] calling init triggers
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_init.py:init():614] starting backend
2025-09-26 12:39:04,656 INFO    MainThread:27471 [wandb_init.py:init():618] setting up manager
2025-09-26 12:39:04,659 INFO    MainThread:27471 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-09-26 12:39:04,659 INFO    MainThread:27471 [wandb_init.py:init():624] backend started and connected
2025-09-26 12:39:04,665 INFO    MainThread:27471 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2025-09-26 12:39:04,665 INFO    MainThread:27471 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-09-26 12:39:04,665 INFO    MainThread:27471 [wandb_init.py:init():716] updated telemetry
2025-09-26 12:39:04,678 INFO    MainThread:27471 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-09-26 12:40:36,539 ERROR   MainThread:27471 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-09-26 12:40:36,617 ERROR   MainThread:27471 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/ieyeppo/.pyenv/versions/nlp_py3_11_9/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/ieyeppo/.pyenv/versions/nlp_py3_11_9/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
