2025-09-26 12:53:23,138 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-09-26 12:53:23,138 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Configure stats pid to 39565
2025-09-26 12:53:23,138 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Loading settings from /home/ieyeppo/.config/wandb/settings
2025-09-26 12:53:23,138 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Loading settings from /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/base/wandb/settings
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_init.py:_log_setup():524] Logging user logs to /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/base/wandb/run-20250926_125323-fdrudrek/logs/debug.log
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_init.py:_log_setup():525] Logging internal logs to /home/ieyeppo/AI_Lab/natural-language-processing-competition/notebooks/base/wandb/run-20250926_125323-fdrudrek/logs/debug-internal.log
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_init.py:init():564] calling init triggers
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_init.py:init():589] re-initializing run, found existing run on stack: imgczz0d
2025-09-26 12:53:23,139 INFO    MainThread:39565 [wandb_run.py:_finish():1962] finishing run ieyeppo/nlp-competition/imgczz0d
2025-09-26 12:53:23,139 INFO    MainThread:39565 [jupyter.py:save_history():445] not saving jupyter history
2025-09-26 12:53:23,140 INFO    MainThread:39565 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2025-09-26 12:53:23,140 INFO    MainThread:39565 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2025-09-26 12:53:23,140 INFO    MainThread:39565 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2025-09-26 12:53:23,140 INFO    MainThread:39565 [wandb_run.py:_restore():2185] restore
2025-09-26 12:53:23,140 INFO    MainThread:39565 [wandb_run.py:_restore():2191] restore done
2025-09-26 12:53:29,416 INFO    MainThread:39565 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2025-09-26 12:53:29,416 INFO    MainThread:39565 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2025-09-26 12:53:29,418 INFO    MainThread:39565 [wandb_run.py:_footer_sync_info():3796] logging synced files
2025-09-26 12:53:29,495 INFO    MainThread:39565 [wandb_init.py:init():614] starting backend
2025-09-26 12:53:29,496 INFO    MainThread:39565 [wandb_init.py:init():618] setting up manager
2025-09-26 12:53:29,497 INFO    MainThread:39565 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-09-26 12:53:29,498 INFO    MainThread:39565 [wandb_init.py:init():624] backend started and connected
2025-09-26 12:53:29,504 INFO    MainThread:39565 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2025-09-26 12:53:29,504 INFO    MainThread:39565 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-09-26 12:53:29,504 INFO    MainThread:39565 [wandb_init.py:init():716] updated telemetry
2025-09-26 12:53:29,507 INFO    MainThread:39565 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-09-26 12:53:31,165 INFO    MainThread:39565 [wandb_run.py:_on_init():2254] communicating current version
2025-09-26 12:53:31,261 INFO    MainThread:39565 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.22.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-09-26 12:53:31,261 INFO    MainThread:39565 [wandb_init.py:init():800] starting run threads in backend
2025-09-26 12:53:31,281 INFO    MainThread:39565 [wandb_run.py:_console_start():2233] atexit reg
2025-09-26 12:53:31,282 INFO    MainThread:39565 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2025-09-26 12:53:31,282 INFO    MainThread:39565 [wandb_run.py:_redirect():2153] Wrapping output streams.
2025-09-26 12:53:31,282 INFO    MainThread:39565 [wandb_run.py:_redirect():2178] Redirects installed.
2025-09-26 12:53:31,283 INFO    MainThread:39565 [wandb_init.py:init():841] run started, returning control to user process
